groups:
- name: instance-health
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 20s
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} is down"
      description: "The instance {{ $labels.instance }} has been unreachable for more than 20 seconds."