name: ft_transcendence

services:
  r_proxy:
    container_name: r_proxy
    restart: on-failure
    build:
        context: ./reverse_proxy
        dockerfile: Dockerfile
    ports:
        - 443:443
    networks:
      - router

  auth-service:
    container_name: auth-service
    restart: on-failure
    volumes:
      - ./back/auth-service/asset/srcs:/usr/src/auth-service/asset/srcs
    environment:
      API_CREDENTIAL: ${API_CREDENTIAL:?}
      JWT_SECRET: ${JWT_SECRET:?}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:?}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:?}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:?}
      NODE_ENV: ${NODE_ENV:?}
      MAIL_ADRESS: ${MAIL_ADRESS}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_SECURE: ${MAIL_SECURE}
      MAIL_SERVICE: ${MAIL_SERVICE}
    build:
        context: ./back/auth-service
        dockerfile: Dockerfile
        args:
          NODE_ENV: ${NODE_ENV:?}
    expose:
      - 3000
    networks:
      - router

  chat-service:
    container_name: chat-service
    restart: on-failure
    volumes:
      - ./back/chat-service/asset/srcs:/usr/src/chat-service/srcs
      - db-chat:/usr/src/chat-service/asset/prisma/db
    environment:
      NODE_ENV: ${NODE_ENV:?}
      JWT_SECRET: ${JWT_SECRET:?}
      DATABASE_URL: ${DATABASE_URL:?}
      API_CREDENTIAL: ${API_CREDENTIAL:?}
    build:
        context: ./back/chat-service
        dockerfile: Dockerfile
        args:
          NODE_ENV: ${NODE_ENV:?}
          DATABASE_URL: ${DATABASE_URL:?}
    expose:
      - 3000
    ports:
      - 9874:5555
    networks:
      - router

  game-service:
    container_name: game-service
    restart: on-failure
    volumes:
      - ./back/game-service/asset/srcs:/usr/src/game-service/asset/srcs
      - db-game:/usr/src/game-service/prisma/db
    environment:
      DATABASE_URL: ${DATABASE_URL:?}
      API_CREDENTIAL: ${API_CREDENTIAL:?}
      NODE_ENV: ${NODE_ENV:?}
      JWT_SECRET: ${JWT_SECRET:?}
    build:
        context: ./back/game-service
        dockerfile: Dockerfile
        args:
          NODE_ENV: ${NODE_ENV:?}
          DATABASE_URL: ${DATABASE_URL:?}
    expose:
      - 3000
    networks:
      - router

  upload-service:
    container_name: upload-service
    restart: on-failure
    volumes:
      - ./back/upload-service/asset/srcs:/usr/src/upload-service/asset/srcs
      - db-upload:/usr/src/upload-service/uploads
    environment:
      DATABASE_URL: ${DATABASE_URL:?}
      API_CREDENTIAL: ${API_CREDENTIAL:?}
      NODE_ENV: ${NODE_ENV:?}
    build:
        context: ./back/upload-service
        dockerfile: Dockerfile
        args:
          NODE_ENV: ${NODE_ENV:?}
    expose:
      - 3000
    networks:
      - router


  user-service:
    container_name: user-service
    restart: on-failure
    volumes:
      - ./back/user-service/asset/srcs:/usr/src/user-service/asset/srcs
      - db-user:/usr/src/user-service/asset/prisma/db
    environment:
      API_CREDENTIAL: ${API_CREDENTIAL:?}
      JWT_SECRET: ${JWT_SECRET:?}
      NODE_ENV: ${NODE_ENV:?}
    build:
        context: ./back/user-service
        dockerfile: Dockerfile
        args:
          NODE_ENV: ${NODE_ENV:?}
          DATABASE_URL: ${DATABASE_URL:?}
    ports:
      - 5555:5555
    expose:
      - 3000
    networks:
      - router

  front_dev:
    container_name: front_dev
    restart: on-failure
    build:
        context: ./front/
        dockerfile: Dockerfile
    expose:
      - 5173
    volumes:
      - ./front/vitejs:/var/www/html
    networks:
      - router

volumes:
  db-chat:
  db-user:
  db-game:
  db-upload:
networks:
  router:
    driver: bridge