name: ft_transcendence

services:
  r_proxy:
    container_name: r_proxy
    restart: on-failure
    build:
        context: ./back/reverse_proxy
        dockerfile: Dockerfile
    ports:
        - 443:443
    networks:
      - router
  api_gateway:
    container_name: api_gateway
    restart: on-failure
    build:
        context: ./back/api_gateway
        dockerfile: Dockerfile
    expose:
      - 3000
    networks:
      - router
      - services
  front_dev:
    container_name: front_dev
    restart: on-failure
    build:
        context: ./front/
        dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - data-front:/var/www/html
    networks:
      - services
volumes:
  data-front:
    name: data-front
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./front/vitejs
networks:
  services:
    driver: bridge
  router:
    driver: bridgename: ft_transcendence