name: ft_transcendence

services:
  r_proxy:
    container_name: r_proxy
    restart: on-failure
    build:
        context: ./reverse_proxy
        dockerfile: Dockerfile
    ports:
        - 443:443
    networks:
      - router

  api_gateway:
    container_name: api_gateway
    restart: on-failure
    volumes:
      - api-gateway:/usr/src/api_gateway/db
    environment:
      - DATABASE_URL=${DATABASE_URL:?}
    build:
        context: ./back/api_gateway
        dockerfile: Dockerfile
    ports:
      - 5555:5555
    expose:
      - 3000
    networks:
      - router
      - services

  front_dev:
    container_name: front_dev
    restart: on-failure
    build:
        context: ./front/
        dockerfile: Dockerfile
    expose:
      - 5173
    volumes:
      - data-front:/var/www/html
    networks:
      - router

volumes:
  api-gateway:
    name: api-gateway
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./back/api_gateway/asset/db
  data-front:
    name: data-front
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./front/vitejs

networks:
  services:
    driver: bridge
  router:
    driver: bridge