{
 "title": "ft_transcendence",
 "description": "  ",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(probe_success{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Servce status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "chat:status:now{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "scrape_duration_seconds{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "auth:status:now{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Probe Phases Duration",
     "type": "timeseries",
     "description": "Duration of http request by phase, summed over all redirects",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    }
   ]
  }
 ]
}