route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email_receiver'

receivers:
- name: 'email_receiver'
  email_configs:
    - to: '${ALERTMANAGER_TARGET_MAIL}'
      smarthost: '${ALERTMANAGER_SMTP_SMARTHOST}'
      from: '${ALERTMANAGER_SMTP_FROM}'
      auth_username: '${ALERTMANAGER_SMTP_AUTH_USERNAME}'
      auth_password: '${ALERTMANAGER_SMTP_AUTH_PASSWORD}'
      auth_identity: '${ALERTMANAGER_SMTP_AUTH_USERNAME}'
      require_tls: true
